In [1]:
%load_ext autoreload
%autoreload 2

## Import packages

In [2]:
import argo_utils.argo_utils as argo_utils

import cProfile, pstats
import numpy as np
import pandas as pd

---

# convert_conditions_to_argo_string

In [3]:
l = [
    ('col_cat', '<=', 0.5), ('col_cat', '>', 0.5), ('col_float', '>=', 1.1), ('col_int', '>=', 1.2)
]

In [4]:
list_of_conditions = l * 1000000

In [5]:
columns_int = ['col_int']
columns_cat = ['col_cat']

## OLD

In [6]:
filename = 'convert_conditions_to_argo_string_old'

In [7]:
cProfile.run('argo_utils.convert_conditions_to_argo_string(list_of_conditions, columns_int, columns_cat)', sort='cumtime', filename=f'{filename}.dat')

In [8]:
p = pstats.Stats(f'{filename}.dat')
p.sort_stats('cumtime').print_stats()

Mon Jan 18 13:42:32 2021    convert_conditions_to_argo_string_old.dat

         6000006 function calls in 3.418 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    3.418    3.418 {built-in method builtins.exec}
        1    0.154    0.154    3.418    3.418 <string>:1(<module>)
        1    1.980    1.980    3.263    3.263 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:10(convert_conditions_to_argo_string)
        1    0.452    0.452    0.452    0.452 {method 'sort' of 'list' objects}
  1000000    0.249    0.000    0.351    0.000 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:25(convert_values_for_columns_int)
  4000000    0.240    0.000    0.240    0.000 {method 'append' of 'list' objects}
        1    0.240    0.240    0.240    0.240 {method 'join' of 'str' objects}
  1000000    0.103    0.000    0.103    0.000 {b

Already fast enough.

# clean_dup_features_from_conditions

In [9]:
l = [
    ('col_cat', '<=', 0.5), ('col_cat', '<', 0.3), ('col_float', '>=', 1.1), ('col_float', '>=', 1.2)
]

In [10]:
list_of_conditions = l * 1000000

## OLD

In [11]:
filename = 'clean_dup_features_from_conditions_old'

In [12]:
cProfile.run('argo_utils.clean_dup_features_from_conditions(list_of_conditions)', sort='cumtime', filename=f'{filename}.dat')

In [13]:
p = pstats.Stats(f'{filename}.dat')
p.sort_stats('cumtime').print_stats()

Mon Jan 18 13:45:13 2021    clean_dup_features_from_conditions_old.dat

         16 function calls in 1.062 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    1.062    1.062 {built-in method builtins.exec}
        1    0.000    0.000    1.062    1.062 <string>:1(<module>)
        1    0.000    0.000    1.062    1.062 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:54(clean_dup_features_from_conditions)
        1    0.007    0.007    0.722    0.722 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:74(<listcomp>)
        3    0.000    0.000    0.715    0.238 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:65(dedupe_conditions)
        3    0.664    0.221    0.664    0.221 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:67(<listcomp>)
       

# return_columns_types

In [3]:
import pandas as pd
import numpy as np

In [4]:
X = pd.DataFrame({
    'int_col': np.random.randint(0, 10, 1000000),
    'ohe_cat_col': np.random.randint(0, 2, 1000000),
    'float_col': np.random.uniform(0, 1, 1000000)
})

In [5]:
_range = range(0, 100)

In [6]:
X_list = [X for i in _range]

In [7]:
col_name = [(f'int_col{i}', f'ohe_cat_col{i}', f'float_col{i}')for i in _range]

In [8]:
col_name = [c for t in col_name for c in t]

In [9]:
X_big = pd.concat(X_list, axis=1)

In [10]:
X_big.shape

(1000000, 300)

In [11]:
X_big.columns = col_name

## OLD

In [63]:
filename = 'return_columns_types'

In [64]:
cProfile.run('argo_utils.return_columns_types(X_big)', sort='cumtime', filename=f'{filename}.dat')

In [65]:
p = pstats.Stats(f'{filename}.dat')
p.sort_stats('cumtime').print_stats()

Mon Jan 18 13:58:59 2021    return_columns_types.dat

         307795 function calls (306124 primitive calls) in 16.455 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   16.455   16.455 {built-in method builtins.exec}
        1    0.000    0.000   16.455   16.455 <string>:1(<module>)
        1    0.481    0.481   16.455   16.455 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:96(return_columns_types)
        1    0.000    0.000    7.151    7.151 /Users/jlaidler/venvs/argo/lib/python3.7/site-packages/pandas/core/generic.py:11389(stat_func)
        1    0.000    0.000    7.151    7.151 /Users/jlaidler/venvs/argo/lib/python3.7/site-packages/pandas/core/frame.py:8531(_reduce)
      601    0.001    0.000    6.220    0.010 /Users/jlaidler/venvs/argo/lib/python3.7/site-packages/pandas/core/generic.py:5197(_protect_consolidate)
        1    0.000    0.000    6.21

In [79]:
%%timeit 
X_values = X.values
(X_values - X_values.round()).sum(axis=0) == 0

22.6 ms ± 894 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [91]:
%timeit (X - X.round()).sum(axis=0) == 0

26.6 ms ± 2.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [101]:
%%timeit 
unique_values = X['int_col'].unique()
unique_values.sort()

6.45 ms ± 282 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [94]:
%timeit np.unique(X['int_col'].values)

31.5 ms ± 1.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [98]:
%timeit set(X['int_col'].values)

118 ms ± 2.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [99]:
[1, 2] == [1, 2]

True

In [100]:
X['int_col'].unique()

array([3, 7, 1, 8, 0, 5, 4, 9, 6, 2])

In [102]:
unique_values = X['int_col'].unique()
unique_values.sort()

In [105]:
unique_values == [1, 2]

/Users/jlaidler/venvs/argo/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

Can't easily improve, already pretty quick.

# return_binary_pred_perf_of_set_numpy

In [12]:
X_rules = X_big >= 0.9

In [13]:
y = np.random.randint(0, 2, 1000000)

In [14]:
perf = argo_utils.return_binary_pred_perf_of_set_numpy(y_true=y, y_preds=X_rules, y_preds_columns=X_rules.columns)
'150.19109999999998'

'150.19109999999998'

## OLD

In [111]:
filename = 'return_binary_pred_perf_of_set_numpy_no_opt_or_weight_old'

In [114]:
cProfile.run('argo_utils.return_binary_pred_perf_of_set_numpy(y_true=y, y_preds=X_rules, y_preds_columns=X_rules.columns)', sort='cumtime', filename=f'{filename}.dat')

In [115]:
p = pstats.Stats(f'{filename}.dat')
p.sort_stats('cumtime').print_stats()

Mon Jan 18 14:23:02 2021    return_binary_pred_perf_of_set_numpy_no_opt_or_weight_old.dat

         1524 function calls (1504 primitive calls) in 5.990 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    5.990    5.990 {built-in method builtins.exec}
        1    0.377    0.377    5.989    5.989 <string>:1(<module>)
        1    2.319    2.319    5.613    5.613 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:139(return_binary_pred_perf_of_set_numpy)
        4    1.795    0.449    1.795    0.449 {method 'reduce' of 'numpy.ufunc' objects}
     14/4    0.000    0.000    1.495    0.374 {built-in method numpy.core._multiarray_umath.implement_array_function}
        1    0.000    0.000    1.494    1.494 <__array_function__ internals>:2(tile)
        1    0.000    0.000    1.494    1.494 /Users/jlaidler/venvs/argo/lib/python3.7/site-packages/numpy/lib/shape_base.

## OLD (with weight)

In [63]:
filename = 'return_binary_pred_perf_of_set_numpy_no_opt_with_weight_old'

In [19]:
weights = np.random.randint(0, 10, X_rules.shape[0])

In [65]:
cProfile.run('argo_utils.return_binary_pred_perf_of_set_numpy(y_true=y, y_preds=X_rules, y_preds_columns=X_rules.columns, sample_weight=weights)', sort='cumtime', filename=f'{filename}.dat')

In [66]:
p = pstats.Stats(f'{filename}.dat')
p.sort_stats('cumtime').print_stats()

Mon Jan 18 15:18:01 2021    return_binary_pred_perf_of_set_numpy_no_opt_with_weight_old.dat

         3391 function calls (3365 primitive calls) in 31.095 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   31.095   31.095 {built-in method builtins.exec}
        1    0.787    0.787   31.095   31.095 <string>:1(<module>)
        1   13.496   13.496   30.307   30.307 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:139(return_binary_pred_perf_of_set_numpy)
        4    8.630    2.158    8.630    2.158 {method 'reduce' of 'numpy.ufunc' objects}
     21/6    0.012    0.001    8.137    1.356 {built-in method numpy.core._multiarray_umath.implement_array_function}
        3    0.002    0.001    7.981    2.660 {method 'sum' of 'numpy.ndarray' objects}
        3    0.000    0.000    7.980    2.660 /Users/jlaidler/venvs/argo/lib/python3.7/site-packages/numpy/core/_met

## NEW (with weight)

In [90]:
filename = 'return_binary_pred_perf_of_set_numpy_no_opt_with_weight_new'

In [91]:
cProfile.run('argo_utils.return_binary_pred_perf_of_set_numpy(y_true=y, y_preds=X_rules, y_preds_columns=X_rules.columns, sample_weight=weights)', sort='cumtime', filename=f'{filename}.dat')

In [92]:
p = pstats.Stats(f'{filename}.dat')
p.sort_stats('cumtime').print_stats()

Mon Jan 18 15:33:09 2021    return_binary_pred_perf_of_set_numpy_no_opt_with_weight_new.dat

         1539 function calls (1519 primitive calls) in 19.449 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   19.449   19.449 {built-in method builtins.exec}
        1    0.695    0.695   19.449   19.449 <string>:1(<module>)
        1   10.100   10.100   18.754   18.754 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:139(return_binary_pred_perf_of_set_numpy)
        4    5.733    1.433    5.733    1.433 {method 'reduce' of 'numpy.ufunc' objects}
        3    0.001    0.000    4.339    1.446 {method 'sum' of 'numpy.ndarray' objects}
        3    0.000    0.000    4.339    1.446 /Users/jlaidler/venvs/argo/lib/python3.7/site-packages/numpy/core/_methods.py:45(_sum)
     15/5    0.001    0.000    2.913    0.583 {built-in method numpy.core._multiarray_umath.implement

## NEW (with weight and opt_func)

In [20]:
from rule_optimisation.optimisation_functions import Precision
precision = Precision()

In [17]:
filename = 'return_binary_pred_perf_of_set_numpy_with_opt_and_weight_new'

In [21]:
cProfile.run('argo_utils.return_binary_pred_perf_of_set_numpy(y_true=y, y_preds=X_rules, y_preds_columns=X_rules.columns, sample_weight=weights, opt_func=precision.fit)', sort='cumtime', filename=f'{filename}.dat')

In [22]:
p = pstats.Stats(f'{filename}.dat')
p.sort_stats('cumtime').print_stats()

Mon Jan 18 16:59:39 2021    return_binary_pred_perf_of_set_numpy_with_opt_and_weight_new.dat

         755314 function calls (745496 primitive calls) in 28.322 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.001    0.001   28.322   28.322 {built-in method builtins.exec}
        1    0.891    0.891   28.321   28.321 <string>:1(<module>)
    301/1   17.849    0.059   27.430   27.430 /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py:139(return_binary_pred_perf_of_set_numpy)
   3921/6    0.015    0.000    7.566    1.261 {built-in method numpy.core._multiarray_umath.implement_array_function}
     1204    5.066    0.004    5.066    0.004 {method 'reduce' of 'numpy.ufunc' objects}
        1    0.000    0.000    3.983    3.983 <__array_function__ internals>:2(apply_along_axis)
        1    0.002    0.002    3.983    3.983 /Users/jlaidler/venvs/argo/lib/python3.7/site-packages/n

In [95]:
X_rules_ones = np.ones((X_rules.shape[0], X_rules.shape[1]))

In [102]:
%timeit y_arr = X_rules_ones * y[:, None]

1.54 s ± 112 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [103]:
%timeit y_arr_old = np.tile(y, (X_rules.shape[1], 1)).T

1.45 s ± 31.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
y_rep = np.repeat(y, X_rules.shape[1])

In [16]:
y_rep.shape

(300000000,)

In [110]:
y.shape

(1000000,)

In [112]:
np.broadcast_to(y, (1, y.shape[0]))

array([[1, 0, 0, ..., 1, 0, 1]])

In [108]:
np.broadcast_to(y, (X_rules.shape[0], X_rules.shape[1])).shape

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (1000000,) and requested shape (1000000,300)

In [16]:
y_T = y.T

In [20]:
y_T.shape, y.shape

((1000000,), (1000000,))

In [ ]:
np.tile(y, (1, X_rules.shape[0])).shape

In [114]:
np.tile(y, (X_rules.shape[1], 1)).shape

(300, 1000000)

In [101]:
(y_arr == y_arr_old).mean().mean()

1.0

In [84]:
perf_old = argo_utils.return_binary_pred_perf_of_set_numpy(y_true=y, y_preds=X_rules, y_preds_columns=X_rules.columns, sample_weight=weights)

In [82]:
perf_new = argo_utils.return_binary_pred_perf_of_set_numpy(y_true=y, y_preds=X_rules, y_preds_columns=X_rules.columns, sample_weight=weights)

In [85]:
(perf_new == perf_old).mean()

Precision          1.0
Recall             1.0
PercDataFlagged    1.0
OptMetric          0.0
dtype: float64

In [128]:
X_rules_mean_np = X_rules.values.mean(0)

In [122]:
tot_num_records = X_rules.values.shape[0]

In [129]:
X_rules_mean_man = X_rules.values.sum(0)/tot_num_records

In [131]:
X_rules_mean_np == X_rules_mean_man

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [126]:
X_rules.values.sum(0)/tot_num_records

array([0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099974,
       0.900383, 0.501554, 0.099974, 0.900383, 0.501554, 0.099

In [4]:
import string

In [10]:
np.random.seed(0)
y_preds = pd.DataFrame(np.random.randint(0, 2, size=(1000, 10)), columns=[
                       i for i in string.ascii_letters[:10]])
y_true = pd.Series(np.random.randint(0, 2, 1000))
sample_weight = y_true * 10

In [12]:
argo_utils.return_binary_pred_perf_of_set_numpy(y_true=y_true, y_preds=y_preds, y_preds_columns=y_preds.columns)

Precision    Recall  PercDataFlagged OptMetric
a   0.509728  0.513725            0.514      None
b   0.518664  0.517647            0.509      None
c   0.513462  0.523529            0.520      None
d   0.533597  0.529412            0.506      None
e   0.532803  0.525490            0.503      None
f   0.545455  0.529412            0.495      None
g   0.507216  0.482353            0.485      None
h   0.516252  0.529412            0.523      None
i   0.507576  0.525490            0.528      None
j   0.505976  0.498039            0.502      None

In [143]:
y_preds['a'].mean(0)

0.514

In [25]:
X_rules_sum = X_rules.values.sum(0)

In [27]:
%%timeit
X_rules_sum/X_rules.shape[0]

3.03 µs ± 384 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
%%timeit
X_rules.mean()

265 ms ± 18.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [33]:
%load_ext memory_profiler

In [36]:
%memit argo_utils.return_binary_pred_perf_of_set_numpy(y_true=y_true, y_preds=y_preds, y_preds_columns=y_preds.columns)

peak memory: 2610.25 MiB, increment: -0.53 MiB


In [44]:
from rule_optimisation.optimisation_functions import Precision
precision = Precision()

In [49]:
import sys
print(sys.getsizeof(y_preds))
print(sys.getsizeof(y_true))

80152
8152


In [51]:
from argo_utils.argo_utils import return_binary_pred_perf_of_set_numpy

In [52]:
%mprun -f return_binary_pred_perf_of_set_numpy return_binary_pred_perf_of_set_numpy(y_true=y, y_preds=X_rules, y_preds_columns=X_rules.columns)#, opt_func=precision.fit)

Filename: /Users/jlaidler/Documents/tigress/tigress/argo/argo/argo_utils/argo_utils/argo_utils.py

Line #    Mem usage    Increment  Occurences   Line Contents
   139   1233.7 MiB   1233.7 MiB           1   def return_binary_pred_perf_of_set_numpy(y_true: np.ndarray, y_preds: np.ndarray, y_preds_columns: list,
   140                                                                                  sample_weight=None, opt_func=None) -> pd.DataFrame:
   141                                             """
   142                                             Calculates the performance of a set of binary predictors given a target column.
   143                                         
   144                                             Args:
   145                                                 y_true (np.ndarray): Binary integer target column.
   146                                                 y_preds (np.ndarray): Set of binary integer predictors. Can also be a single predictor.
   147  

In [60]:
np.divide(np.array([1,2,3]), np.array([1,0,3]))

/Users/jlaidler/venvs/argo/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 1., inf,  1.])